services:
#### Form Types ####
    positibe_orm_block.abstract_simple_form:
        class: Positibe\Bundle\OrmBlockBundle\Form\Type\AbstractBlockType
        tags:
            - { name: form.type, alias: positibe_abstract_block }

#### Block Service ####
    positibe_orm_block.action_block_service:
        class: Positibe\Bundle\OrmBlockBundle\Block\Service\ActionBlockService
        arguments: ['positibe_orm_block.action_block_service', @templating]
        calls:
            - [ setContainer, [@service_container]]
        tags:
            - { name: sonata.block }

#### Services and Utils ####
    positibe_orm_block.orm_block_loader:
        class: Positibe\Bundle\OrmBlockBundle\Block\Loader\OrmBlockLoader
        arguments: [@doctrine.orm.entity_manager, @cmf_core.publish_workflow.checker]
        tags:
            - { name: sonata.block.loader }

    positibe_orm_block.block.cache.js_sync:
        class: Positibe\Bundle\OrmBlockBundle\Cache\BlockJsCache
        arguments: [@router, @sonata.block.renderer, @sonata.block.loader.chain, @sonata.block.context_manager, true]
        tags:
            - { name: sonata.cache }

    positibe_orm_block.block.cache.js_async:
        class: Positibe\Bundle\OrmBlockBundle\Cache\BlockJsCache
        arguments: [@router, @sonata.block.renderer, @sonata.block.loader.chain, @sonata.block.context_manager, false]
        tags:
            - { name: sonata.cache }